function onIngles() {
    document.getElementById('subtitulo').innerHTML = 'Front-end Developer & UI/UX Designer'
    document.getElementById('profileTitle').innerHTML = 'MY PROFILE'
    document.getElementById('text1').innerHTML = 'Front-End Developer and Graphic Designer, I dedicate myself to create and develop visually pleasing interfaces for websites and applications, seeking to bring a good integration of the user with the system. I am a dedicated and hardworking professional, I look for ways to stand out and do everything with excellence.'
    document.getElementById('formationTitle').innerHTML = 'ACADEMIC EDUCATION'
    document.getElementById('text2').innerHTML = 'Bachelor in Information Systems'
    document.getElementById('text3').innerHTML = 'Vila Velha University (2022 - until now)'
    document.getElementById('vltTitle').innerHTML = 'VOLUNTEERING'
    document.getElementById('ejuvv').innerHTML = 'EJUVV'
    document.getElementById('text4').innerHTML = 'Project Direction (2021-2022)'
    document.getElementById('text5').innerHTML = 'At Junior Enterprise (JE) I worked as a project consultant. I acquired practical and theoretical experience in execution, agility and quality in deliveries.'
    document.getElementById('skillsTitle').innerHTML = 'SKILLS'
    document.getElementById('softTitle').innerHTML = 'SOFT'
    document.getElementById('hardTitle').innerHTML = 'HARD'
    document.getElementById('s1').innerHTML = 'Critical Thinking'
    document.getElementById('s2').innerHTML = 'Commitment'
    document.getElementById('s3').innerHTML = 'Fast learning'
    document.getElementById('s4').innerHTML = 'Teamwork'
    document.getElementById('s5').innerHTML = 'Focus on Results'
    document.getElementById('s6').innerHTML = 'Planning Capacity'
    document.getElementById('s7').innerHTML = 'Communication'
    document.getElementById('h1').innerHTML = 'Office Suite'
    document.getElementById('h2').innerHTML = 'Adobe Photoshop'
    document.getElementById('h3').innerHTML = 'Adobe After Effects'
    document.getElementById('h4').innerHTML = 'Canva'
    document.getElementById('h5').innerHTML = 'HTML'
    document.getElementById('h6').innerHTML = 'CSS'
    document.getElementById('h7').innerHTML = 'English & Portuguese'
    document.getElementById('m1').innerHTML = 'HOME'
    document.getElementById('m2').innerHTML = 'PROFILE'
    document.getElementById('m3').innerHTML = 'ACADEMIC EDUCATION'
    document.getElementById('m4').innerHTML = 'VOLUNTEERING'
    document.getElementById('m5').innerHTML = 'SKILLS'
    document.getElementById('m6').innerHTML = 'CONTACT'
    document.getElementById('contactTitle').innerHTML = 'MY CONTACT'

}

function onPortugues() {
    document.getElementById('subtitulo').innerHTML = 'Desenvolvedor Front-end & Designer UI/UX'
    document.getElementById('profileTitle').innerHTML = 'PERFIL'
    document.getElementById('text1').innerHTML = 'Programador Front-End e Desinger Gráfico, me dedico a criar e desenvolver interfaces visualmente agradáveis para sites e aplicativos, buscando trazer    uma boa integração do usuario com o sistema. Sou um profissional dedicado e esforçado, busco maneiras de me destacar e realizar tudo com excelência.'
    document.getElementById('formationTitle').innerHTML = 'FORMAÇÃO ACADÊMICA'
    document.getElementById('text2').innerHTML = 'Bacharelado em Sistemas de Informação'
    document.getElementById('text3').innerHTML = 'Universidade Vila Velha (2022 - cursando)'
    document.getElementById('vltTitle').innerHTML = 'TRABALHO VOLUNTÁRIO'
    document.getElementById('ejuvv').innerHTML = 'EJUVV'
    document.getElementById('text4').innerHTML = 'Diretoria de Projetos (2021-2022)'
    document.getElementById('text5').innerHTML = 'No Movimento Empresa Júnior (MEJ) atuei como consultor de projetos. Adquiri experiência prática e teórica em execução, agilidade e qualidade nas entregas.'
    document.getElementById('skillsTitle').innerHTML = 'SKILLS'
    document.getElementById('softTitle').innerHTML = 'SOFT'
    document.getElementById('hardTitle').innerHTML = 'HARD'
    document.getElementById('s1').innerHTML = 'Pensamento Crítico'
    document.getElementById('s2').innerHTML = 'Comprometimento'
    document.getElementById('s3').innerHTML = 'Aprendizagem Rápida'
    document.getElementById('s4').innerHTML = 'Trabalho em Equipe'
    document.getElementById('s5').innerHTML = 'Foco em Resultado'
    document.getElementById('s6').innerHTML = 'Capacidade de Planejamento'
    document.getElementById('s7').innerHTML = 'Comunicação'
    document.getElementById('h1').innerHTML = 'Pacote Office'
    document.getElementById('h2').innerHTML = 'Adobe Photoshop'
    document.getElementById('h3').innerHTML = 'Adobe After Effects'
    document.getElementById('h4').innerHTML = 'Canva'
    document.getElementById('h5').innerHTML = 'HTML'
    document.getElementById('h6').innerHTML = 'CSS'
    document.getElementById('h7').innerHTML = 'Inglês'
    document.getElementById('m1').innerHTML = 'HOME'
    document.getElementById('m2').innerHTML = 'PERFIL'
    document.getElementById('m3').innerHTML = 'FORMAÇÃO ACADÊMICA'
    document.getElementById('m4').innerHTML = 'TRABALHO VOLUNTÁRIO'
    document.getElementById('m5').innerHTML = 'SKILLS'
    document.getElementById('m6').innerHTML = 'CONTATO'
    document.getElementById('contactTitle').innerHTML = 'CONTATO'

}